### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [DarinkaTownsend/ISII-WORKSHOP-HOTELES#1]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by DarinkaTownsend** [comment]
We have added the requested functionalities. You can see in the Issue_management branch, ID commit : 8c85ddab01674d4d1710958c72b3e48da6dfab4b

**Comment by DarinkaTownsend** [comment]
“We will proceed to process the request, @jaialarcon   will be the assigned analyst, @DarinkaTownsend  will develop the solution, and @keanceva  will perform the tests”

**Comment by DarinkaTownsend** [comment]
[Cost of adding the new features.pdf](https://github.com/DarinkaTownsend/ISII-WORKSHOP-HOTELES/files/7900357/Cost.of.adding.the.new.features.pdf)

Please @jose598 review the analysis carried out by @jaialarcon  where he indicates the costs involved in adding the new functionalities

**Comment by jose598** [comment]
Hello @DarinkaTownsend I was taking a look your documents. I know that you will test all cases applied for solving this issue as well as possible, however for me it's important that know if you calculation follows all rules demanded. So, I'd like that you send me a table with all cases/rules applied for getting the insurance cost result. 



Thank you!

**Comment by DarinkaTownsend** [comment]
[Test Plan and Cost.pdf](https://github.com/DarinkaTownsend/ISII-WORKSHOP-HOTELES/files/7902366/Test.Plan.and.Cost.pdf)

Please @jose598 review the analysis carried out by @jaialarcon where he indicates the costs involved in adding the new functionalities and the test with all cases

**Comment by jose598** [comment]
@DarinkaTownsend Just one observation: The discount for the first case mentioned on the issue is $100 by the couple, it means $50 for each one. Please change this and then you can start working on it.

**Comment by DarinkaTownsend** [comment]
[Update Test Plan and Cost.pdf](https://github.com/DarinkaTownsend/ISII-WORKSHOP-HOTELES/files/7902436/Update.Test.Plan.and.Cost.pdf)
 Got it!

**Comment by DarinkaTownsend** [comment]
The new functionalities have already been implemented by @DarinkaTownsend , it can be found in the comit: 7fd7ce83501d1808ca2af144a2b1229648e262ad

**Comment by DarinkaTownsend** [comment]
https://github.com/DarinkaTownsend/ISII-WORKSHOP-HOTELES/blob/7fd7ce83501d1808ca2af144a2b1229648e262ad/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java

**Comment by DarinkaTownsend** [comment]
[Test Plan Done.pdf](https://github.com/DarinkaTownsend/ISII-WORKSHOP-HOTELES/files/7902551/Test.Plan.Done.pdf)

This is our Test Plan @jose598 , all the cases passed at the second time, we had to correct the code. You can find our correction code in this commit : 979f17555a271f006b5bbed9cdff700993bc7cbf

https://github.com/DarinkaTownsend/ISII-WORKSHOP-HOTELES/blob/550df8a4a0b143be72bbbf8d995a31dc7cd0738d/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java

**Comment by jose598** [comment]
Sorry @DarinkaTownsend. Maybe I didn't explain better in the issue. On the commit your are considering the issue like on rules applied, it means if has 30 or less than 60 the discount is 100(that is ok) but the case when she has more than 60 should be considering like another case, no include in the before.

**Comment by DarinkaTownsend** [comment]
@jose598 I still don't understand about the discount for people who are over 60. How much money should be reduced from the base of 600?

**Comment by jose598** [comment]
Nothing. I checked it out again and everything is OK.

**Comment by jose598** [comment]
I already use the changes. Everything is OK.
Thank you for your support.

**Comment by DarinkaTownsend** [comment]
@jose598 You can use our program in any interpreter that accepts Java, when running the program all the inputs are validated and in case of having an incorrect input, everything will return a message.

**Comment by DarinkaTownsend** [comment]
@jose598 Are you satisfied with our program and what recommendations could you give us?

**Comment by jose598** [comment]
Yes I'm 

@DarinkaTownsend

**Comment by DarinkaTownsend** [comment]
Got it!
